.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2023 
.\"
.TH hostsysinfo 1 
.SH NAME
hostsysinfo \- generates a file of system parameters
.SH SYNOPSIS
.B hostsysinfo  [ \- debug ] [ \-verbose ]
.SH DESCRIPTION
The 
.B hostsysinfo
generates a file of system parameters
.SH AUTHORS
The
.B hostsysinfo
program was written by 
Mike
.PP
This document was written by Mike <test@test.com> for Debian.
